services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    env_file:
      - .env  
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd-network

  hello-demo:
    image: hello-demo:latest
    container_name: hello-demo-app
    ports:
      - "8081:8081"
    networks:
      - cicd-network
    depends_on:
      - jenkins

networks:
  cicd-network:
    driver: bridge

volumes:
  jenkins_home: