jenkins:
  systemMessage: "Jenkins configured using JCasC"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - file: /usr/share/jenkins/ref/job-dsl/hello-demo-multibranch-pipeline.groovy