jenkins:
  systemMessage: "Jenkins configured using JCasC"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "dockerhub-creds"
              username: "quashed"
              password: "${DOCKERHUB_TOKEN}"
              description: "Docker Hub credentials"

jobs:
  - file: /usr/share/jenkins/ref/job-dsl/hello-demo-multibranch-pipeline.groovy